# Generated by Django 4.1.7 on 2023-02-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("ratings", models.DecimalField(decimal_places=1, max_digits=3)),
                ("image_url", models.URLField()),
                ("shop_id", models.CharField(max_length=500)),
                ("item_id", models.CharField(max_length=500)),
            ],
        ),
    ]
