# Generated by Django 3.2.18 on 2023-03-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=20, null=True)),
                ('item_id', models.CharField(max_length=20, null=True)),
                ('product_url', models.URLField(null=True)),
                ('product_name', models.CharField(max_length=400, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(null=True)),
                ('shop_location', models.CharField(max_length=100, null=True)),
                ('shop_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
