# Generated by Django 4.1.7 on 2023-02-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexing_project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="price",
        ),
        migrations.RemoveField(
            model_name="products",
            name="ratings",
        ),
        migrations.AddField(
            model_name="products",
            name="category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="current_price",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="item_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="items_sold",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="original_price",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="product_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="rating_star",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="shop_follower_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="shop_location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="shop_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="shop_place",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="shop_rating_bad",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="shop_rating_good",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="shop_rating_normal",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="shop_ratings",
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="shop_response_rate",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="shop_response_time",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="shop_username",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="template_tags",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="time",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="total_rating",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="user_id",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="image_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="item_id",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="shop_id",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
