# Generated by Django 4.1.7 on 2023-02-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "indexing_project",
            "0002_remove_products_price_remove_products_ratings_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
