# Generated by Django 3.2.18 on 2023-03-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing_project', '0003_alter_products_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='products',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='item_count',
        ),
        migrations.RemoveField(
            model_name='products',
            name='items_sold',
        ),
        migrations.RemoveField(
            model_name='products',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rating_star',
        ),
        migrations.RemoveField(
            model_name='products',
            name='shop_follower_count',
        ),
        migrations.RemoveField(
            model_name='products',
            name='shop_place',
        ),
        migrations.RemoveField(
            model_name='products',
            name='shop_rating_bad',
        ),
        migrations.RemoveField(
            model_name='products',
            name='shop_rating_good',
        ),
        migrations.RemoveField(
            model_name='products',
            name='shop_rating_normal',
        ),
        migrations.RemoveField(
            model_name='products',
            name='shop_response_rate',
        ),
        migrations.RemoveField(
            model_name='products',
            name='shop_response_time',
        ),
        migrations.RemoveField(
            model_name='products',
            name='shop_username',
        ),
        migrations.RemoveField(
            model_name='products',
            name='template_tags',
        ),
        migrations.RemoveField(
            model_name='products',
            name='time',
        ),
        migrations.RemoveField(
            model_name='products',
            name='total_rating',
        ),
        migrations.RemoveField(
            model_name='products',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='username',
        ),
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
